python3 encode.py --encoder ../cfg/x264.yml \
--input_csv ../../datasets/info/codec/hevc_sdr_ctc_meta_info.csv \
--input_dir ../../datasets/hevc_sdr_ctc/ori \
--core 4 \
--output ../result/hevc_sdr_ctc/ori/x264 \
--metrics psnr psnr_hvsm ssim ms_ssim vmaf vmaf_neg \
--db ../result/hevc_sdr_ctc/ori/x264/result.db \
--fps 25 \
--frame_num 1 \
--enc_mode CQP \
--qp_list 27,32,37,42