# general settings
name: train_MobileIENet_Lite_DIVKON2K
arch_type: GeneralLRJNDModel
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 123
split_num: 1
save_final_results_path: './experiments/MobileIENet_Lite_DIVKON2K_5splits_results.txt'

# dataset and data loader settings
datasets:
  train:
    name: general_jnd_dataset
    type: GeneralFRDataset

    dataroot_in: ./datasets/divkon_2k_yuv/ori
    dataroot_ref: ./datasets/divkon_2k_yuv/tob_kang_2023_filter_5
    meta_info_file: ./datasets/info/train/divkon_2k_yuv_meta_info.csv
    split_file: ./datasets/info/train/divkon_2k_yuv_5_splits.pkl
    split_index: 1

    augment:
      center_crop: 224
      hflip: 1
      vflip: 1
      rot90: 1
    img_range: 1

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 4
    prefetch_mode: ~

  val:
    name: general_jnd_dataset
    type: GeneralFRDataset

    dataroot_in: ./datasets/divkon_2k_yuv/ori
    dataroot_ref: ./datasets/divkon_2k_yuv/tob_kang_2023_filter_5
    meta_info_file: ./datasets/info/train/divkon_2k_yuv_meta_info.csv
    split_file: ./datasets/info/train/divkon_2k_yuv_5_splits.pkl
    split_index: 1

# network structures
network:
  type: MobileIENet_Lite
  in_channels: 3
  out_channels: 3
  head_channels: 8
  body_channels: 8
  tail_channels: 12
  rep_scale: 4
  only_train_y: true

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  target: image

  supervised: true

  optim:
    type: Adam
    lr: !!float 3e-4
    weight_decay: !!float 1e-6

  scheduler:
    type: CosineAnnealingLR
    T_max: 97000
    eta_min: !!float 1e-6

  total_iter: 100000
  warmup_iter: 3000

  # losses
  fidelity_loss_opt:
    - type: CharbonnierLoss
      loss_weight: !!float 1.0
    - type: Dct8ResidualEnergyLoss
      loss_weight: !!float 0.02

  rate_loss_opt:
    - type: Dct8HFConstraintLoss
      loss_weight: !!float 0.02
      zigzag_cutoff: 10
      low_band_weight: 1.0
      high_band_weight: 1.0

  perceptual_loss_opt:
    - type: MsssimLoss
      loss_weight: !!float 0.16
  
# validation settings
val:
  val_freq: !!float 1000
  save_img: false
  pbar: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: true
    ssim: # metric name, can be arbitrary
      type: calculate_ssim
      crop_border: 0
      test_y_channel: true

# logging settings
logger:
  print_freq: 200
  save_latest_freq: !!float 5e2
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500